{
 "title": "CNV - Alerts Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "source",
    "query": "All : + 0, External (!RH\\,!IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal=\"\"})), Internal (RH\\,IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal!=\"\"}))"
   },
   {
    "name": "hco_installed",
    "query": "+ on (_id) group_left(_blah) ( 0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))"
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(ocm_subscription, _id)"
    }
   },
   {
    "name": "severity",
    "label": "Alert Severity",
    "query": "All : severity=~\".*\"\\,, critical : severity=~\"critical\"\\,, warning : severity=~\"warning\"\\,, info : severity=~\"info\"\\,"
   },
   {
    "name": "kubernetes_operator_part_of",
    "label": "Operator Name",
    "query": "All : All=~\"\", kubevirt : kubernetes_operator_part_of=~\"kubevirt\""
   },
   {
    "name": "alert_name",
    "label": "Alerts Name",
    "query": "query_result(count by (alertname) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\"} $hco_installed $source ))"
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts by Severity",
   "type": "table",
   "description": "This panel shows the  number of impacted HCO clusters by the alert severity and the % out of the total HCO clusters. ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (severity) (count by (_id, severity) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} $hco_installed $source ))"
    },
    {
     "expr": "count by (severity) (count by (_id, severity) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} $hco_installed $source )) / on() group_left() count (count by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"} $source ))"
    }
   ]
  },
  {
   "title": "Alerts by Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity, cnv_version)(\n    alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} \n         + on(_id) group_left(cnv_version) (0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))\n    $hco_installed $source \n)"
    },
    {
     "expr": "count by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity, cnv_version)(\n    sum by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity, cnv_version,_id)(\n    0*alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} \n    + on(_id) group_left(cnv_version) (0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))\n    $hco_installed $source \n))"
    },
    {
     "expr": "(count by (cnv_version)( count by (_id,cnv_version) ((0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))) $source )) + on(cnv_version) group_left()(0* count by(cnv_version)(0*alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"}\n    + on(_id) group_left(cnv_version) (0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))\n    $hco_installed $source ))"
    },
    {
     "expr": "(count by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity, cnv_version)(\n    sum by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity, cnv_version,_id)(\n    0*alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} \n    + on(_id) group_left(cnv_version) (0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))\n    $hco_installed $source \n)))\n/\non(cnv_version) group_left() (count by (cnv_version)( count by (_id,cnv_version) ((0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))) $source )) + on(cnv_version) group_left()(0* count by(cnv_version)(0*alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"}\n    + on(_id) group_left(cnv_version) (0*topk by (_id)(1,label_replace(csv_succeeded{name=~\".*hyperconverged.*\"},\"cnv_version\", \"$1\", \"version\", \"([0-9]+\\\\.[0-9]+)\\\\..*\")))\n    $hco_installed $source ))"
    }
   ]
  },
  {
   "title": "Alerts by Name",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity) \n(\n  count by (alertname, _id, kubernetes_operator_part_of, kubernetes_operator_component, severity) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} $hco_installed $source )\n) "
    },
    {
     "expr": "sum by (alertname, kubernetes_operator_part_of, kubernetes_operator_component, severity) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} $hco_installed $source )"
    }
   ]
  },
  {
   "title": "Clusters Impacted By the Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count by (_id) (alerts{$severity $kubernetes_operator_part_of, _id=~\"$cluster_id\", alertname!~\"Watchdog\", alertname=~\"$alert_name\"} $hco_installed $source ) + on (_id) group_left(email_domain, ebs_account) (0 * topk by (_id) (1, ocm_subscription{} $hco_installed $source )) + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"}))"
    }
   ]
  }
 ]
}