{
 "title": "CNV - Cluster Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "All : + 0, External (!RH\\,!IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal=\"\"})), Internal (RH\\,IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal!=\"\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count $source)"
    }
   ]
  },
  {
   "title": "Clusters by Version",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc ((count by (version) (csv_succeeded{name=~\".*hyperconverged.*\"} $source)) > 5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by Minor Version",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc ((count by (major_minor_version) (label_replace(\n  csv_succeeded{name=~\".*hyperconverged.*\"},\n  \"major_minor_version\",\n  \"$1.$2\",  # Replacement format to keep only Major and Minor version numbers.\n  \"version\",\n  \"(\\\\d+)\\\\.(\\\\d+)\\\\..*\"  # Regex to match and capture Major and Minor version numbers.\n)\n $source)) > 5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by Version",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc ((count by (version) (csv_succeeded{name=~\".*hyperconverged.*\"} $source)) > 5)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Clusters by Channel",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (channel)(label_replace(subscription_sync_total{installed=~\".*hyperconverged.*\"}, \"channel\", \"none\", \"channel\", \"\") $source) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters with CNV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(_id)(subscription_sync_total{installed=~\".*hyperconverged.*\"} $source))\n"
    }
   ]
  },
  {
   "title": "Accounts with CNV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    count by (ebs_account)\n    (\n      (subscription_sync_total{installed=~\".*hyperconverged.*\"} $source)\n      + on (_id) group_left(ebs_account)\n      (0 * topk by (_id) (1, ocm_subscription{}))\n    )\n)"
    }
   ]
  },
  {
   "title": "Clusters over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (subscription_sync_total{installed=~\".*hyperconverged.*\"} $source)",
     "legendFormat": "HCO Installations"
    }
   ]
  },
  {
   "title": "Running VMs over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count $source)",
     "legendFormat": "Number of Running VMs"
    }
   ]
  },
  {
   "title": "Number of running VMs, Memory, cluster count and CPU Cores By account and email domain",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc\n(\n sum by (_0_email_domain, ebs_account)\n (\n   cnv:vmi_status_running:count $source\n   + on (_id) group_left(_0_email_domain, ebs_account)\n   ( 0 * topk by (_id) (1, label_replace(ocm_subscription,\"_0_email_domain\", \"$1\", \"email_domain\", \"(.*)\")) )\n )>0\n)"
    },
    {
     "expr": "sort_desc\n(\n  sum by (_0_email_domain, ebs_account)(\n         sum by (_id) (cluster:capacity_cpu_cores:sum $source)\n         + on (_id) group_left(_blah)\n         ( 0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}) )\n         + on (_id) group_left(_0_email_domain, ebs_account)\n         ( 0 * topk by (_id) (1, label_replace(ocm_subscription,\"_0_email_domain\", \"$1\", \"email_domain\", \"(.*)\")) )\n         + on (_id) group_left(_blah)\n         ( 0 * group by (_id)(cnv:vmi_status_running:count))\n )\n)"
    },
    {
     "expr": "sort_desc\n(\n  sum by (_0_email_domain, ebs_account)( \n         sum by (_id) (cluster:capacity_memory_bytes:sum $source)\n         + on (_id) group_left(_blah)\n         ( 0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}) )\n         + on (_id) group_left(_0_email_domain, ebs_account)\n         ( 0 * topk by (_id) ( 1, label_replace(ocm_subscription{},\"_0_email_domain\", \"$1\", \"email_domain\", \"(.*)\")) )\n         + on (_id) group_left(_blah)\n         ( 0 * group by (_id)(cnv:vmi_status_running:count))\n )\n)"
    },
    {
     "expr": "sort_desc\n    (\n      sum by (_0_email_domain, ebs_account)(\n      1 + 0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"})\n      + on (_id) group_left(_blah) (0 * group by (_id, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal=\"\"}))\n       + on (_id) group_left(_0_email_domain, ebs_account)( 0 * topk by (_id) (1, label_replace(ocm_subscription{},\"_0_email_domain\", \"$1\", \"email_domain\", \"(.*)\") ) ) \n       + on (_id) group_left(_blah)( 0 * group by (_id)(cnv:vmi_status_running:count)))   \n     )"
    }
   ]
  },
  {
   "title": "Number of OLM subscriptions by email domain and account",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc\n(\n count by (_0_email_domain, ebs_account)\n (\n   (\n     subscription_sync_total{installed=~\".*hyperconverged.*\"} $source\n   )\n   + on (_id) group_left(_0_email_domain, ebs_account)\n   ( 0 * topk by (_id) (1, label_replace(ocm_subscription{},\"_0_email_domain\", \"$1\", \"email_domain\", \"(.*)\")  )  ) \n )\n)"
    }
   ]
  },
  { "title": "Cluster Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Clusters with Additional Network",
   "type": "stat",
   "description": "Number of CNV clusters that have at least one instance (pods and/or vms) annotated with k8s.v1.cni.cncf.io/networks. ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (_id) (cluster:network_attachment_definition_instances:max $source + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))))"
    }
   ]
  },
  {
   "title": "Clusters by Additional Network Name",
   "type": "piechart",
   "description": "Number of CNV clusters that have instances (pods and/or vms) annotated with k8s.v1.cni.cncf.io/networks, by network name.",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (count by (networks) (count by (networks, _id)\n  ((cluster:network_attachment_definition_instances:max{networks=~\"^[^,]*$\", networks!~\"any|bridge|cnv-bridge|tuning|cnv-tuning|sriov|ib-sriov\"} $source)\n  + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))\n)))",
     "legendFormat": "__auto"
    },
    {
     "expr": " count (count by (_id)\n  ((cluster:network_attachment_definition_instances:max{networks=~\"bridge|cnv-bridge\"} $source)\n  + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": " count (count by (_id)\n  ((cluster:network_attachment_definition_instances:max{networks=~\"tuning|cnv-tuning\"} $source)\n  + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))\n))",
     "legendFormat": "__auto"
    },
    {
     "expr": " count (count by (_id)\n  ((cluster:network_attachment_definition_instances:max{networks=~\"sriov|ib-sriov\"} $source)\n  + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by Multiple Additional Networks Names",
   "type": "piechart",
   "description": "Number of CNV clusters by that have instances (pods and/or VMs) with 2 or more network names annotated with k8s.v1.cni.cncf.io/networks, by networks names.",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (count by (networks) (count by (networks, _id)\n  ((cluster:network_attachment_definition_instances:max{networks=~\".*,.*\"} $source)\n  + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))\n)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters without Additional Networks",
   "type": "stat",
   "description": "Number of CNV clusters that do not have any instances (pods and/or vms) annotated with k8s.v1.cni.cncf.io/networks.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(count by(_id)(subscription_sync_total{installed=~\".*hyperconverged.*\"} $source))) - (count(count by (_id) ((cluster:network_attachment_definition_instances:max $source + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))))))\n"
    }
   ]
  },
  {
   "title": "Clusters with Additional Network %",
   "type": "stat",
   "description": "Percentage of CNV clusters that have at least one instance (pods and/or vms) annotated with k8s.v1.cni.cncf.io/networks. ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(count by (_id) (cluster:network_attachment_definition_instances:max $source + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))))) / (count(count by(_id)(subscription_sync_total{installed=~\".*hyperconverged.*\"} $source)))"
    }
   ]
  },
  {
   "title": "Clusters without Additional Networks %",
   "type": "stat",
   "description": "Percentage of CNV clusters that do not have any instances (pods and/or vms) annotated with k8s.v1.cni.cncf.io/networks.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((count(count by(_id)(subscription_sync_total{installed=~\".*hyperconverged.*\"} $source))) - (count(count by (_id) ((cluster:network_attachment_definition_instances:max $source + on(_id) group_left(_blah) (0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))))))) / (count(count by(_id)(subscription_sync_total{installed=~\".*hyperconverged.*\"} $source)))\n"
    }
   ]
  },
  { "title": "Virtual Machins Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Operating System Distribution",
   "type": "piechart",
   "description": "This panel shows the OSs distribution, for all running VMs that include the os label , that was introduced in OCP 4.8.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (os) (cnv:vmi_status_running:count{os=\"<none>\"} $source))",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sort_desc (sum by (os) (cnv:vmi_status_running:count{os!=\"\",os!=\"<none>\"} $source))",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Flavor Distribution",
   "type": "piechart",
   "description": "This panel shows the flavors distribution, for all running VMs that include the flavor label , that was introduced in OCP 4.8.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (flavor) (cnv:vmi_status_running:count{flavor=\"<none>\"} $source))",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sort_desc (sum by (flavor) (cnv:vmi_status_running:count{flavor!=\"\",flavor!=\"<none>\"} $source))",
     "legendFormat": "{{flavor}}"
    }
   ]
  },
  {
   "title": "Workload Distribution",
   "type": "piechart",
   "description": "This panel shows the OSs distribution, for all running VMs that include the os label , that was introduced in OCP 4.8.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (workload) (cnv:vmi_status_running:count{workload=\"<none>\"} $source))",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sort_desc (sum by (workload) (cnv:vmi_status_running:count{workload!=\"\",workload!=\"<none>\"} $source))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Host Type Distribution",
   "type": "piechart",
   "description": "This panel shows the cluster host type distribution, for clusters with running VMs.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host_type) (count by (_id,host_type) (id_primary_host_type)\n+ on (_id) group_left(_blah) (0 * group by (_id) (cnv:vmi_status_running:count) $source))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guest OS Name Distribution",
   "type": "piechart",
   "description": "This panel shows the guest OS name distribution. This information was introduced in CNV v4.16.0, for all running VMs that have the guest agent installed.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (guest_os_name)(cnv:vmi_status_running:count{guest_os_name!=\"\", guest_os_name!=\"<none>\"} $source))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Type Distribution",
   "type": "piechart",
   "description": "This panel shows the instance types distribution, for all running VMs that include the instance type annotation.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (instance_type) (cnv:vmi_status_running:count{instance_type!=\"\",instance_type!=\"<none>\", instance_type!=\"<other>\"} $source))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Preference Distribution",
   "type": "piechart",
   "description": "This panel shows the preferences distribution, for all running VMs that include the preference annotation.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (sum by (preference) (cnv:vmi_status_running:count{preference!=\"\",preference!=\"<none>\", preference!=\"<other>\"} $source))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Guest OS Name and Version ID",
   "type": "table",
   "description": "This table shows a list of guest OSs name and Version ID. This information was introduced in CNV v4.16.0, for all running VMs that have the guest agent installed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc (sum by (guest_os_name, guest_os_version_id)(cnv:vmi_status_running:count{guest_os_name!=\"\", guest_os_name!=\"<none>\"} $source))",
     "legendFormat": "Guest OS Name: {{guest_os_name}}, Guest OS Version ID: {{guest_os_version_id}}"
    }
   ]
  },
  {
   "title": "VM Templates",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc (sum by (os,flavor,workload) (cnv:vmi_status_running:count{os!=\"\",os!=\"<none>\",flavor!=\"\",flavor!=\"<none>\",workload!=\"\",workload!=\"<none>\" } $source))",
     "legendFormat": "OS: {{os}}, Flavor: {{flavor}}, Workload: {{workload}}"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "README.md",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "options": {
    "content": "\n### CSV Condition Reasons\n\nThe following table provides a short description of what the condition means:\n\n\n| **Condition Reason**                        | **Explanation for Telemetry**                                                                                                                              | **Operator is running**                 |\n| ------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |\n| RequirementsUnknown                         | OLM hasn't gotten around to checking for requirements yet                                                                                                  | no                                      |\n| RequirementsNotMet                          | One or more requirements to install haven't been met (crds, nativeapis, apis, serviceaccount, rbac)                                                        | no                                      |\n| AllRequirementsMet                          | The Operator is currently installing and all of its requirements have been met                                                                             | No (installing)                         |\n| OwnerConflict                               | Two operators own the same apis in the namespace, but are not connected via a chain of \"replaces\" (rare, mostly caused by a bug in 4.2)                    | no                                      |\n| InstallComponentFailed                      | Failed to create a component that makes up the Operator: deployment, CRD, RBAC apiservices, etc.                                                           | no                                      |\n| InvalidInstallStrategy                      | The install strategy for a csv is not in the format we expect.                                                                                             | no                                      | \n| InstallWaiting                              | Install is progressing and OLM is waiting for components to come online.                                                                                   | No (Installing)                         |\n| InstallSucceeded                            | The operator's deployments are all ready/available.                                                                                                        | yes                                     |\n| InstallCheckFailed                          | The operator never became healthy, OLM now treats the operator as failed.                                                                                  | no                                      |\n| ComponentUnhealthy                          | Some requirement or component is not in the state it should be, the Operator will be flipped back in an attempt to recreate anything that belongs to it.   | likely no                               |\n| BeingReplaced                               | Operator is being updated                                                                                                                                  | yes                                     |\n| Replaced                                    | Operator has been updated and newer version is healthy                                                                                                     | yes                                     |\n| NeedsReinstall                              | Operator configuration got updated ( subscription.config, rotating certs, proxy config, etc) and the Operator needs to be redeployed with the new settings | yes                                     |\n| NeedsCertRotation                           | The certs will be rotated for an apiservice-based operator.                                                                                                | yes                                     |\n| APIServiceResourceIssue                     | A previously created resource required to deploy an extension apiserver has disappeared.                                                                   | likely no                               |\n| APIServiceResourcesNeedReinstall            | Some resources required to run extension apiservers were not in the expected state, OLM will attempt to recreate them.                                     | likely no                               |\n| APIServiceInstallFailed                     | Extension apiserver install has failed in a way that OLM can't recover.                                                                                    | no                                      |\n| Copied                                      | This CSV is a placeholder to indicate the operator is watching the current namespace.                                                                      | Yes (depends on the parent, \"real\" csv) |\n| InvalidInstallModes                         | The CSV contains improperly formatted installmodes (duplicate entries, typos, etc)                                                                         | no                                      |\n| NoTargetNamespaces                          | There are no namespaces resolved as target namespaces for the current operatorgroup.                                                                       | no                                      |\n| UnsupportedOperatorGroup                    | The current operatorgroup does not support the installmodes of the Operator.                                                                               | no                                      |\n| NoOperatorGroup                             | Operator cannot be installed because the namespace does not have an OperatorGroup.                                                                         | no                                      |\n| TooManyOperatorGroups                       | We currently only allow 1 OperatorGroup per namespace.                                                                                                     | no                                      |\n| InterOperatorGroupOwnerConflict             | The operator provides an API that another operator provides in the current namespace (i.e. it is provided in an operatorgroup that targets this namespace) | no                                      |\n| CannotModifyStaticOperatorGroupProvidedAPIs | A CSV is present in an operatorgroup with \"static\" provided apis set and provides apis not in the set.                                                     |                                         |"
   }
  },
  {
   "title": "Number of OLM CSVs install/upgrade failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (phase, reason) (csv_abnormal{name=~\".*hyperconverged.*\", phase=~\"Pending|Failed\"} $source )"
    }
   ]
  },
  {
   "title": "Clusters with OLM CSVs issues in the last 1 hour",
   "type": "table",
   "description": "Clusters with CSV issues in the last 1 Hour and the value indicates the time they have this issue.\n\nNote: The max value van be up to 3 weeks, depending that we have 3 weeks of data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (_id,name,phase,reason, email_domain) (\n count_over_time(csv_abnormal{name=~\".*hyperconverged.*\", phase=~\"Pending|Failed\"}[1h])\n  + on (_id) group_left(email_domain)\n  ( 0 * topk by (_id) (1, ocm_subscription{} ))\n  $source \n) * 0 \n+ on (_id,name,phase,reason) group_left(_blah) (\nsum by (_id,name,phase,reason, email_domain) (\ncount_over_time(csv_abnormal{name=~\".*hyperconverged.*\", phase=~\"Pending|Failed\"}[3w:1d])\n  $source \n)\n)"
    }
   ]
  },
  {
   "title": "Clusters with abnormal OLM CSVs",
   "type": "table",
   "description": "Could indicate update problems",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (_id,name,phase,reason, email_domain) (\n  csv_abnormal{name=~\".*hyperconverged.*\", phase=~\"Pending|Failed\"} \n  + on (_id) group_left(email_domain)\n  ( 0 * topk by (_id) (1, ocm_subscription{} ))\n  $source \n)"
    }
   ]
  }
 ]
}