{
 "title": "CNV - Single Alert Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "source",
    "label": "Source",
    "query": "All : + 0, External (!RH\\,!IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal=\"\"})), Internal (RH\\,IBM) : + on (_id) group_left(_blah) (0 * group by (_id\\, email_domain) (id_version_ebs_account_internal:cluster_subscribed{internal!=\"\"}))"
   },
   {
    "name": "hco_installed",
    "query": "+ on (_id) group_left(_blah) ( 0 * group by (_id) (subscription_sync_total{installed=~\".*hyperconverged.*\"}))"
   },
   {
    "name": "severity",
    "label": "Alert Severity",
    "query": "All : severity=~\".*\"\\,, critical : severity=~\"critical\"\\,, warning : severity=~\"warning\"\\,, info : severity=~\"info\"\\,"
   },
   {
    "name": "kubernetes_operator_part_of",
    "label": "Operator Name",
    "query": "All : All=~\"\", kubevirt : kubernetes_operator_part_of=~\"kubevirt\""
   },
   {
    "name": "alert_name",
    "label": "Alerts Name",
    "query": {
     "query": "query_result(count by (alertname) (alerts{$severity $kubernetes_operator_part_of, alertname!~\"Watchdog\"} $hco_installed $source))"
    }
   },
   {
    "name": "source_version_values",
    "query": {
     "query": "query_result(count by (version) (cluster_version{type=\"current\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts fired",
   "type": "stat",
   "description": "The max number of alerts over the selected time period",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (alertname, severity)(alerts{alertname=\"$alert_name\"} $hco_installed $source)[5m:1h])",
     "legendFormat": "{{alertname}} ({{severity}})"
    }
   ]
  },
  {
   "title": "Alerts fired by Version",
   "type": "table",
   "description": "Number of alerts fired by version sampled per hour, during the selected time period.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\n    sum by (version)(alerts{alertname=\"$alert_name\"}\n    + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"}))\n    $source\n    ) [5m:1h]\n)",
     "legendFormat": "{{cnv_version}}"
    }
   ]
  },
  {
   "title": "Impacted Clusters by Version",
   "type": "table",
   "description": "Number of impacted clusters by version sampled per hour, during the selected time period.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\n    count by (version) (\n        sum by (version, _id)(0*alerts{alertname=\"$alert_name\"}\n        + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"})) $source\n        )\n    )[5m:1h]\n)",
     "legendFormat": "{{cnv_version}}"
    }
   ]
  },
  {
   "title": "Impacted Clusters / Total Clusters - by Version",
   "type": "table",
   "description": "Number of impacted clusters percentage sampled per hour, during the selected time period.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(\n    count by (version) (\n        sum by (version, _id)(0*alerts{alertname=\"$alert_name\"}\n        + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"})) $source)\n    ) [5m:1h]\n)\n/ on (version) group_left()\nmax_over_time(\n    count by (version) (\n        count by (version, _id)(0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"}) $source)\n    ) [5m:1h]\n)",
     "legendFormat": "{{cnv_version}}"
    }
   ]
  },
  {
   "title": "Alerts Fired by Cluster",
   "type": "table",
   "description": "latest value of the number of alerts fired per cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (version, _id, email_domain, ebs_account)(alerts{alertname=\"$alert_name\"}\n    + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"}))\n    + on (_id) group_left(email_domain, ebs_account)( 0 * topk by (_id) (1, ocm_subscription{}))\n    $source\n)",
     "legendFormat": "{{_id}} ({{cnv_version}}, {{email_domain}}, {{ebs_account}})"
    }
   ]
  },
  {
   "title": "Impacted Clusters by Account",
   "type": "table",
   "description": "latest value of the number of impacted clusters per account.\nFor accounts with multiple email domains, one random domain will appear.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (version, email_domain, ebs_account) (\n    sum by (version, _id, email_domain, ebs_account)(alerts{alertname=\"$alert_name\"} \n        + on(_id) group_left(version) (0*topk by (_id)(1,csv_succeeded{name=~\".*hyperconverged.*\"})) \n        + on (_id) group_left(ebs_account)( 0 * topk by (_id) (1, ocm_subscription{}))\n        # take only 1 email_domain per account to sum by accont only\n        + on (ebs_account) group_left(email_domain)( 1 * topk by (ebs_account) (1, ocm_subscription{})) \n        $source\n    )\n)",
     "legendFormat": "{{email_domain}}, {{ebs_account}} ({{cnv_version}})"
    }
   ]
  }
 ]
}