{
 "title": "Memcached Overview",
 "tags": [ "observatorium" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(memcached_commands_total, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(memcached_commands_total{namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(memcached_commands_total{namespace=~\"$namespace\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\", command=\"get\", status=\"hit\"}[1m])) / sum(rate(memcached_commands_total{namespace=~\"$namespace\", job=~\"$job\", command=\"get\"}[1m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (job, instance) (rate(memcached_commands_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{command}} {{status}}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (rate(memcached_items_evicted_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stored",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (rate(memcached_items_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (memcached_current_bytes{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (memcached_current_items{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (rate(memcached_connections_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}} - Connection Rate"
    },
    {
     "expr": "sum without (job) (memcached_current_connections{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Current Connrections"
    },
    {
     "expr": "sum without (job) (memcached_max_connections{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Max Connections"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (rate(memcached_read_bytes_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum without (job) (rate(memcached_written_bytes_total{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memcached Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memcached Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (job, instance, version) (memcached_version{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "max by (job, instance) (memcached_uptime_seconds{namespace=~\"$namespace\", job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  }
 ]
}