{
 "title": "RHOBS Metrics SLOs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   { "name": "tenant", "label": "Tenant", "query": "label_values(tenant)" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays the SLOs as defined in the [RHOBS Service Level Objectives](https://docs.google.com/document/d/1wJjcpgg-r8rlnOtRiqWGv0zwr1MB6WwkQED1XDWXVQs/edit) document."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API > Metrics Read > Ad Hoc > Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">99.5% of valid /query requests return successfully</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=\"query\",code=~\"5.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=\"query\",code!~\"4.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=\"query\",code=~\"5.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=\"query\",code!~\"4.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n    ) - 0.995\n)\n/\n(1 - 0.995), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">99.5% of valid /query_range requests return successfully</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=~\"query_range\",code=~\"5.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=~\"query_range\",code!~\"4.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=~\"query_range\",code=~\"5.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-api\",group=\"metricsv1\",handler=~\"query_range\",code!~\"4.+\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n    ) - 0.995\n)\n/\n(1 - 0.995), 0)\n"
    }
   ]
  },
  {
   "title": "API > Metrics Read > Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests for /query return < 5s</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(http_request_duration_seconds_bucket{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query\",le=\"5\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n            /\n            sum(rate(http_request_duration_seconds_count{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests for /query_range return < 30s</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(http_request_duration_seconds_bucket{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query_range\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query_range\",le=\"30\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n            /\n            sum(rate(http_request_duration_seconds_count{job=\"observatorium-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"query_range\",namespace=\"$namespace\",tenant=\"$tenant\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  }
 ]
}