{
 "title": "Observatorium API",
 "description": "The Observatorium API is the entrypoint for read and write requests",
 "tags": [ "observatorium" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "job",
    "query": "label_values(http_requests_total, job)"
   },
   {
    "name": "handler",
    "query": "label_values(http_requests_total{job=\"$job\"}, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "/query & /query_legacy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability 1s [28d] > 95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=~\"query|query_legacy\",le=\"1\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=~\"query|query_legacy\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability 3s [28d] > 99%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"query\",le=\"3\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"query\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\", handler=~\"query|query_legacy\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\", handler=~\"query|query_legacy\",code=~\"5..\"}[5m]))\n/\nscalar(sum(rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=~\"query|query_legacy\"}[5m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\", handler=~\"query|query_legacy\",code!~\"5..\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=~\"query|query_legacy\",code!~\"5..\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\", handler=~\"query|query_legacy\",code!~\"5..\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "/query_range",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability 60s [28d] > 90%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\",le=\"60\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability 120s [28d] > 99%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\",le=\"120\",code!~\"5..\"}[28d]))\n/\nsum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\",code=~\"5..\"}[5m])) / \nscalar(sum(rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"query_range\"}[5m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"job$\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Availability (write) 60s [28d] > 95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"rules\",le=\"60\",method=\"PUT\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"rules\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability (read) 60s [28d] > 90%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"rules\",method=\"GET\",le=\"60\",code!~\"5..\"}[28d]))\n/\nsum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"rules\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules\",code=~\"5..\"}[5m])) / scalar(sum(rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules\"}[5m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Availability (write) 60s [28d] > 95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\",le=\"60\",method=\"PUT\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability (read) 60s [28d] > 90%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\",method=\"GET\",le=\"60\",code!~\"5..\"}[28d]))\n/\nsum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\",code=~\"5..\"}[5m])) / scalar(sum(rate(http_requests_total{namespace=\"$namespace\", job=\"$job\",handler=\"rules-raw\"}[5m])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules-raw\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules-raw\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",code!~\"5..\",handler=\"rules-raw\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "RED for $handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "handler",
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\", handler=~\"$handler\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{namespace=\"$namespace\", job=\"$job\", handler=~\"$handler\",code=~\"5..\"}[5m]))\n/\nscalar(sum(rate(http_requests_total{namespace=\"$namespace\", job=\"$job\", handler=~\"$handler\"}[5m])))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\",handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}