{
 "title": "RHOBS.next metrics collection",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "integration,stage,production" },
   {
    "name": "region",
    "query": "us-east-1,us-west-1,us-west-2,sa-east-1,eu-central-1,eu-west-1,ap-northeast-1,ap-southeast-2"
   },
   {
    "name": "sector",
    "query": {
     "query": "label_values(up{env=\"$env\", region=\"$region\"},sector)"
    }
   },
   {
    "name": "mc_name",
    "query": {
     "query": "label_values(up{region=\"$region\", env=\"$env\", sector=\"$sector\"},mc_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of targets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "count by(mc_name) (up{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(mc_name) (up{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Samples/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_tsdb_head_samples_appended_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out-of-order samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_tsdb_head_out_of_order_samples_appended_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m])) / sum by(mc_name) (rate(prometheus_tsdb_head_samples_appended_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(mc_name) (prometheus_tsdb_head_series{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Added series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max by(mc_name) (rate(prometheus_tsdb_head_series_created_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Remote write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Sent samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_remote_storage_samples_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_remote_storage_samples_failed_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_rule_evaluations_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluation failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mc_name) (rate(prometheus_rule_evaluation_failures_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m])) / sum by(mc_name) (rate(prometheus_rule_evaluations_total{env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compute resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg by(mc_name) (sum by(mc_name,pod) (rate(container_cpu_usage_seconds_total{container!=\"\",namespace=\"openshift-observability-operator\",pod=~\"prometheus-rhobs-hypershift-monitoring-stack.+\",env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(mc_name) (max by(mc_name,pod) (container_memory_working_set_bytes{container!=\"\",namespace=\"openshift-observability-operator\",pod=~\"prometheus-rhobs-hypershift-monitoring-stack.+\",env=~\"$env\",region=~\"$region\",sector=~\"$sector\",mc_name=~\"$mc_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}