{
 "title": "ROSA Observability Metamonitoring Dashboard",
 "description": "Dashboard for checking high-level NFR's for RHOBS ROSA HCP Cells",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "integration,stage,production" },
   {
    "name": "region",
    "query": "us-east-1,us-west-1,us-west-2,sa-east-1"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sector",
    "query": {
     "query": "label_values(hypershift_hostedclusters{region=~\"$region\"},sector)"
    }
   },
   { "name": "local_datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(up,namespace)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows key performance indicators for the RHOBS components running in a given ROSA HCP environment/region/sector. Make sure that you select the proper instance of `local_datasource` matching the current environment/region. For instance, `integration/us-west-2` maps to `rhobsi01uw2`."
   }
  },
  { "title": "ROSA Sectors Targeted ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Hosted Clusters by Region / Sector",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sector, region) (sum by (_mc_id, sector, region) (max without (pod,instance) (hypershift_hostedclusters{region=~\"$region\",sector=~\"$sector\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Management Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (_mc_id) (hypershift_hostedclusters{region=~\"$region\",sector=~\"$sector\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hosted Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max without(pod,instance) (hypershift_hostedclusters{region=~\"$region\",sector=~\"$sector\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hosted Clusters by Management Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(_mc_id, sector, region, platform) (max without(pod, instance) (hypershift_hostedclusters{region=~\"$region\",sector=~\"$sector\"})) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Level Objectives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Metrics / Ingest / Availability (Target 99.9%)",
   "type": "stat",
   "description": "Metrics Ingest availability SLO (99.9% target)",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{group=\"metricsv1\", handler=~\"receive\", code=~\"2.*\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__range])) / sum(increase(http_requests_total{group=\"metricsv1\", handler=~\"receive\", code!~\"4.*\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Metrics / Ingest / Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"rhobs-gateway\",group=\"metricsv1\",handler=~\"receive\",code=~\"5.+\",namespace=~\"$namespace\"}[$__range])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"rhobs-gateway\",group=\"metricsv1\",handler=~\"receive\",code!~\"4.+\",namespace=~\"$namespace\"}[$__range]))\n    ) - 0.995\n)\n/\n(1 - 0.995), 0)\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Logs / Ingest / Availability (Target 99.9%)",
   "type": "stat",
   "description": "Metrics Ingest availability SLO (99.9% target)",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{group=\"logsv1\", handler=~\"otlp\", code=~\"2.*\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__range])) / sum(increase(http_requests_total{group=\"logsv1\", handler=~\"otlp\", code!~\"4.*\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Logs / Ingest / Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"rhobs-gateway\",group=\"logsv1\",handler=~\"otlp\",code=~\"5.+\"}[$__range])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"rhobs-gateway\",group=\"logsv1\",handler=~\"otlp\",code!~\"4.+\"}[$__range]))\n    ) - 0.999\n)\n/\n(1 - 0.999), 0)\n",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Probe / Availability",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "  avg by(monitor_name) (\n    probe_success{\n      private=\"false\"\n    }\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "API / Receive Request Rate",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{group=\"metricsv1\", handler=~\"receive\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API / OTLP Logs Request Rate",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{group=\"logsv1\", handler=~\"otlp\", job=\"rhobs-gateway\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Observatorium / API / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{ \n    pod=~\"rhobs-gateway.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"rhobs-gateway.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Observatorium / API / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    pod=~\"rhobs-gateway.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=\"rhobs-int\",\n    pod=~\"rhobs-gateway.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Observatorium / API / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(\n    container_cpu_usage_seconds_total{\n      pod=~\"rhobs-gateway.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"rhobs-gateway.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Observatorium / API / Pod / CPU Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      pod=~\"rhobs-gateway.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"rhobs-gateway.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  { "title": "Synthetic Monitoring Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Total HCP Probes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_success{\n  private=\"false\",\n#  env=~\"$env\",region=~\"$region\",sector=~\"$sector\"\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe / Average Latency by Phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (phase) (probe_http_duration_seconds{\n  private=\"false\"\n  #,env=~\"$env\",region=~\"$region\",sector=~\"$sector\"\n})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Probe / Availability",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{private=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe / Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(probe_success{private=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synthetics / Blackbox Prober / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{\n    pod=~\"synthetics-blackbox-prober.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"synthetics-blackbox-prober.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Synthetics / Blackbox Prober / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    pod=~\"synthetics-blackbox-prober.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"synthetics-blackbox-prober.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Synthetics / Blackbox Prober / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=~\"$namespace\",\n      pod=~\"synthetics-blackbox-prober.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"synthetics-blackbox-prober.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Synthetics / Blackbox Prober / Pod / CPU Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      pod=~\"synthetics-blackbox-prober.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"synthetics-blackbox-prober.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  { "title": "Metrics Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Total Active Timeseries",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Series per Ingester",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (prometheus_tsdb_head_series{namespace=~\"$namespace\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Samples appended per Second",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples appended per second per Ingester",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(prometheus_tsdb_head_samples_appended_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Router / Receive Request Rate",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"thanos-receive-router-rhobs\", handler=~\"receive\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Router / Receive Request Duration",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{handler=\"receive\", job=\"thanos-receive-router-rhobs\",namespace=~\"$namespace\"}[5m]))) * 1",
     "legendFormat": "p50 {{job}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"rhobs-int\", handler=\"receive\", job=\"thanos-receive-router-rhobs\"}[5m]))) * 1",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"rhobs-int\", handler=\"receive\", job=\"thanos-receive-router-rhobs\"}[5m]))) * 1",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Receive / Ingester / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{ \n    pod=~\"thanos-receive-ingester.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "usage {{namespace}}"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-ingester.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "request {{namespace}}"
    }
   ]
  },
  {
   "title": "Receive / Ingester / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    pod=~\"thanos-receive-ingester.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-ingester.*\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Receive / Ingester / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(\n    container_cpu_usage_seconds_total{\n      pod=~\"thanos-receive-ingester.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-ingester.*\",\n    resource=\"cpu\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Receive / Ingester / Pod / CPU Request vs Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      pod=~\"thanos-receive-ingester.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-ingester.*\",\n    resource=\"cpu\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} request"
    }
   ]
  },
  {
   "title": "Receive / Router / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"thanos-receive-router.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "usage {{pod}}"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-router.*\",\n    resource=\"memory\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "request {{pod}}"
    }
   ]
  },
  {
   "title": "Receive / Router / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"thanos-receive-router.*\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-router.*\",\n    resource=\"memory\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Receive / Router / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(\n    container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n      pod=~\"thanos-receive-router.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"thanos-receive-router.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Receive / Router / Pod / CPU Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n      pod=~\"thanos-receive-router.*\",\n      container!=\"\",namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    pod=~\"thanos-receive-router.*\",\n    resource=\"cpu\",namespace=~\"$namespace\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  { "title": "Logs Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Distributor / Bytes received per second",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Distributor/ Bytes received per second per Distributor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(loki_distributor_bytes_received_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingester / Series",
   "type": "stat",
   "description": "Total Timeseries Ingested for RHOBS HCP",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Distributor / Series per second per Ingester",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (loki_ingester_memory_chunks{namespace=~\"$namespace\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Distributor /  Request Rate",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_request_duration_seconds_count{job=\"observatorium-lokistack-distributor-http\",namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Distributor / Request Duration",
   "type": "timeseries",
   "description": "Show rate of incoming /receive requests.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(loki_request_duration_seconds_bucket{namespace=~\"$namespace\", job=\"observatorium-lokistack-distributor-http\"}[5m]))) * 1",
     "legendFormat": "p50 {{job}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(loki_request_duration_seconds_bucket{namespace=\"rhobs-int\", job=\"observatorium-lokistack-distributor-http\"}[5m]))) * 1",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(loki_request_duration_seconds_bucket{namespace=\"rhobs-int\", job=\"observatorium-lokistack-distributor-http\"}[5m]))) * 1",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Distributor / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=~\"$namespace\",\n      pod=~\"observatorium-lokistack-distributor.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace, deployment) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Distributor / Pod / CPU Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=~\"$namespace\",\n      pod=~\"observatorium-lokistack-distributor.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Distributor / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\"\n  }\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (naemspace, deployment) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Distributor / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-distributor.*\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Ingester / Agg. CPU Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(\n    container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n      pod=~\"observatorium-lokistack-ingester.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Ingester / Pod / CPU Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n      pod=~\"observatorium-lokistack-ingester.*\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\",\n    resource=\"cpu\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  },
  {
   "title": "Ingester / Agg. Memory Request & Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\"\n  }\n)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum by (namespace) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\"\n  }\n)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Ingester / Pod / Memory Request vs Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\"\n  }\n)",
     "legendFormat": "{{pod}} - usage"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{ \n    namespace=~\"$namespace\",\n    pod=~\"observatorium-lokistack-ingester.*\"\n  }\n)",
     "legendFormat": "{{pod}} - request"
    }
   ]
  }
 ]
}