{
 "title": "SBR - ETCD by cluster id",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "Cluster ID" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Availability (7d)",
   "type": "stat",
   "description": "The percentage of the last 7 days the cluster has been reported as available - no CVO failure conditions.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum_over_time(max by (_id) ((cluster_version{type=\"failure\",_id=\"$cluster_id\"} * 0 + 1) or (cluster_version{type=\"current\",_id=\"$cluster_id\"}*0))[7d:10m])) / (sum_over_time(max by (_id) (cluster_version{type=\"current\",_id=\"$cluster_id\"} * 0 + 1)[7d:10m]))"
    }
   ]
  },
  {
   "title": "Install Type",
   "type": "stat",
   "description": "\"Others\" means that openshift-install has not been used",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(cluster_installer{_id=\"$cluster_id\"}, \"type\", \"Others\", \"type\", \"other\"), \"type\", \"IPI\", \"type\", \"openshift-install\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{label_node_role_kubernetes_io=\"master\",_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "etcd db size vs used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(instance:etcd_mvcc_db_total_size_in_bytes:sum{_id=\"$cluster_id\"} - instance:etcd_mvcc_db_total_size_in_use_in_bytes:sum{_id=\"$cluster_id\"}) / instance:etcd_mvcc_db_total_size_in_bytes:sum{_id=\"$cluster_id\"} * 100",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "Cloud Provider Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster_infrastructure_provider{_id=\"$cluster_id\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,cluster_version{_id=\"$cluster_id\",type=\"completed\",version!=\"\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Updating To",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1, cluster_version{_id=\"$cluster_id\",type=\"updating\"})",
     "legendFormat": "{{updating}}"
    }
   ]
  },
  {
   "title": "Etcd objects counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (_id) (instance:etcd_object_counts:sum{_id=\"$cluster_id\"})",
     "legendFormat": "etcd objects on Cluster ID {{_id}}"
    }
   ]
  },
  {
   "title": "Etcd objects",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(cluster:usage:resources:sum{_id=\"$cluster_id\"}) by (resource))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd db size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "instance:etcd_mvcc_db_total_size_in_bytes:sum{_id=\"$cluster_id\"}",
     "legendFormat": "db tot size {{instance}}"
    },
    {
     "expr": "instance:etcd_mvcc_db_total_size_in_use_in_bytes:sum{_id=\"$cluster_id\"}",
     "legendFormat": "db tot size in use {{instance}}"
    }
   ]
  },
  {
   "title": "etcd disk backend commit duration seconds < 0.05",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_disk_backend_commit_duration_seconds:histogram_quantile{_id=\"$cluster_id\"} < 0.05",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "etcd disk backend commit duration seconds  > 0.028",
   "type": "timeseries",
   "description": "Everything shown here is BAD",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_disk_backend_commit_duration_seconds:histogram_quantile{_id=\"$cluster_id\"} > 0.028",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "etcd disk wal fsync duration seconds < 0.02",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_disk_wal_fsync_duration_seconds:histogram_quantile{_id=\"$cluster_id\"} < 0.02",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "etcd disk wal fsync duration seconds > 0.013",
   "type": "timeseries",
   "description": "Everything shown here is BAD",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_disk_wal_fsync_duration_seconds:histogram_quantile{_id=\"$cluster_id\"} > 0.013",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "etcd network peer round trip time seconds < 50 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_network_peer_round_trip_time_seconds:histogram_quantile{_id=\"$cluster_id\"} < 0.1",
     "legendFormat": "instance {{instance}}"
    }
   ]
  },
  {
   "title": "etcd network peer round trip time seconds > 52 ms",
   "type": "timeseries",
   "description": "Everything shown here is BAD",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:etcd_network_peer_round_trip_time_seconds:histogram_quantile{_id=\"$cluster_id\"} > 0.052",
     "legendFormat": "instance {{instance}}"
    }
   ]
  }
 ]
}