{
 "title": "Thanos Query Frontend",
 "tags": [
  "thanos-mixin",
  "observatorium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(thanos_status, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{namespace=\"$namespace\", job=~\".*thanos-query-frontend.*\"}, job)"
   },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "Query Frontend API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of requests",
   "type": "timeseries",
   "description": "Shows rate of requests against Query Frontend for the given time.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Rate of queries",
   "type": "timeseries",
   "description": "Shows rate of queries passing through Query Frontend",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(thanos_query_frontend_queries_total{namespace=\"$namespace\", job=~\"$job\", op=\"query_range\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests against Query Frontend.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Show rate of cache requests.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (rate(cortex_cache_request_duration_seconds_count{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Querier cache gets vs misses",
   "type": "timeseries",
   "description": "Show rate of Querier cache gets vs misses.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (rate(querier_cache_gets_total{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Cache gets - {{job}} {{tripperware}}"
    },
    {
     "expr": "sum by (namespace, job, tripperware) (rate(querier_cache_misses_total{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Cache misses - {{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Cortex fetched keys",
   "type": "timeseries",
   "description": "Shows rate of cortex fetched keys.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (rate(cortex_cache_fetched_keys_total{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Cortex cache hits",
   "type": "timeseries",
   "description": "Shows rate of cortex cache hits.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, job, tripperware) (rate(cortex_cache_hits_total{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}