{
 "title": "Thanos Query",
 "tags": [
  "thanos-mixin",
  "observatorium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(thanos_status, namespace)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{namespace=\"$namespace\", job=~\"thanos-query.*\"}, job)"
   },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "Instant Query API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Range Query API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, grpc_method, grpc_code) (rate(grpc_client_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_code) (rate(grpc_client_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval])) / ignoring (grpc_code) group_left() sum by (namespace, job) (rate(grpc_client_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "gRPC (Stream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Streamed gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace,  job, grpc_method, grpc_code) (rate(grpc_client_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_code) (rate(grpc_client_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / ignoring (grpc_code) group_left() sum by (namespace, job) (rate(grpc_client_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of DNS lookups to discover stores.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (namespace, job) (rate(thanos_query_store_apis_dns_lookups_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "lookups {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of failures compared to the total number of executed DNS lookups.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (namespace, job) (rate(thanos_query_store_apis_dns_failures_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])) / sum by (namespace, job) (rate(thanos_query_store_apis_dns_lookups_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Query Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Concurrent Capacity",
   "type": "timeseries",
   "description": "Shows available capacity of processing queries in parallel.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "max_over_time(thanos_query_concurrent_gate_queries_max{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]) - avg_over_time(thanos_query_concurrent_gate_queries_in_flight{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}